# Generated by Django 4.1.1 on 2022-09-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('errorCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErrorBrowser.errorcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbName', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'nowy błąd'), ('unresolved', 'próbowano, ale nie można'), ('resolved', 'rozwiązano')], default='new', max_length=255)),
                ('errorType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ErrorBrowser.errortype')),
            ],
        ),
    ]
